config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create], controller: 'session'

  get "notes(/:title)", to: 'notes#show', as: :note

  resource :network, only: [:show], controller: 'network'
  resource :calendar, only: [:show], controller: 'calendar'

  root to: 'notes#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
# == Schema Information
#
# Table name: blocks
#
#  id              :uuid             not null, primary key
#  child_block_ids :uuid             default([]), not null, is an Array
#  is_note         :boolean          default(FALSE), not null
#  paragraph       :jsonb            not null
#  tags            :string           default([]), not null, is an Array
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  parent_id       :uuid
#  root_note_id    :uuid
#
# Indexes
#
#  index_blocks_on_child_block_ids  (child_block_ids) USING gin
#  index_blocks_on_is_note          (is_note)
#  index_blocks_on_parent_id        (parent_id)
#  index_blocks_on_root_note_id     (root_note_id)
#  index_blocks_on_tags             (tags) USING gin
#  index_blocks_on_title            (title) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (parent_id => blocks.id)
#  fk_rails_...  (root_note_id => blocks.id)
#
class Block < ApplicationRecord
  # 
  # associations
  # 
  belongs_to :parent, class_name: 'Block', optional: true
  belongs_to :root_note, class_name: 'Block', optional: true

  before_destroy :destroy_descendants! # expect to destroy recursively

  def destroy_descendants!
    child_blocks.each(&:destroy!)
  end

  def child_blocks
    # TODO PERFORMANCE
    # 
    # blocks = Block.where(id: ordered_block_ids).map(&:content)
    # NOTE
    # simply `Block.where(id: ordered_block_ids)` will NOT preserve the order of id
    # https://stackoverflow.com/questions/866465/order-by-the-in-value-list
    # 
    child_block_ids.map(&Block.method(:find))
  end

  # from self to root, including self and root
  def ancestor_ids
    current_block = self
    ids = []

    loop do
      ids << current_block.id
      break unless current_block = current_block.parent
    end

    ids
  end

  # TODO
  # - async
  # - service
  after_save :clear_dangling_blocks!, if: :saved_change_to_child_block_ids?

  # 
  # tags
  # 

  taggable_array :tags

  after_save :parse_tags!, if: :saved_change_to_paragraph?

  def parse_tags!
    update! tags: paragraph['content']
      .select{ |node| node['type'] == 'tag' }
      .map{ |node| node['attrs']['tag'] }
      .uniq
  end

  def update_tags_in_paragraph! old_tag, new_tag
    paragraph['content']
      .select{ |node| node['type'] == 'tag' && node['attrs']['tag'] == old_tag }
      .each{ |node| node['attrs']['tag'] = new_tag }
    save!
  end

  # 
  # update notes/nav_channel
  # 

  after_commit -> { Block.refresh_notes_nav }, on: :update, if: :saved_change_to_tags?
  # TODO after_destroy -> { Block.refresh_notes_nav }, if: :is_note

  def self.refresh_notes_nav
    ActionCable.server.broadcast(
      'notes/nav_channel',
      { event: 'notes_updated' }
    )
  end

  # 
  # notes
  # 

  scope :notes, -> { where(is_note: true) }
  scope :not_notes, -> { where(is_note: false) }

  # TODO
  # DEPRECATION WARNING:
  # Class level methods will no longer inherit scoping from `create` in Rails 6.1.
  # To continue using the scoped relation, pass it into the block directly.
  # To instead access the full set of models, as Rails 6.1 will, use `Block.default_scoped`.
  def self.available_tags
    (all_tags + notes.pluck(:title)).uniq.compact
  end

  # TODO make it a service
  # `dangling blocks` i.e. blocks not in child_block_ids anymore
  def clear_dangling_blocks!
    # TODO PERFORMANCE
    # optimize via sql
    # 
    # NOTE is this an active record issue?
    # 
    # > @note.blocks.where.not(id: child_block_ids).destroy_all
    # does not work

    # NOTE not using #child_blocks, to not wasting performance for ordering
    Block.where(parent: self).find_each do |b|
      unless child_block_ids.include? b.id
        b.destroy!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :enforce_login

  private
 
  def enforce_login
    redirect_to new_session_path unless cookies.encrypted[:session_created]
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
  end
end

app/controllers/network_controller.rb
class NetworkController < ApplicationController
  def show
    @nodes = Block.available_tags.map do |tag|
      {
        data: {
          id: tag,
          href: note_path(tag),
        }
      }
    end

    @edges = []
    Block.find_each do |block|
      block.tags.each do |tag|
        @edges << { data: {
          source: block.root_note.title,
          target: tag
        } }
      end
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def show
    @note = Block.notes.find_by(title: params[:title]) ||
      Block.new(
        id: SecureRandom.uuid,
        is_note: true,
        title: params[:title]
      )

    # TODO
    # - exclude current note
    # - group by note
    @linked_blocks = Block.not_notes.with_any_tags @note.title
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :enforce_login, only: [:new, :create]

  def new
  end

  def create
    if ActiveSupport::SecurityUtils::secure_compare(
      params[:session][:password],
      ENV['PASSWORD']
    )
      cookies.encrypted[:session_created] = true
      redirect_to root_path
    else
      flash[:error] = "authentication failed"
      redirect_back fallback_location: root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/network_helper.rb
module NetworkHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def available_tags
    # TODO
    # - titles
    # - PERFORMANCE
    Block.all_tags
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/calendar/show.haml
.col-md-10.bg-light
  = render partial: 'shared/github_corner'

  .row
    .col-md-8.offset-md-2.mt-5
      = month_calendar do |date|
        - title = date.strftime '%F'
        - path = note_path title: title
        - if note = Block.notes.find_by(title: title)
          = link_to path do
            :plain
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-calendar2-check" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10.854 8.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                <path fill-rule="evenodd" d="M14 2H2a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1zM2 1a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2H2z"/>
                <path fill-rule="evenodd" d="M3.5 0a.5.5 0 0 1 .5.5V1a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 .5-.5zm9 0a.5.5 0 0 1 .5.5V1a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 .5-.5z"/>
                <path d="M2.5 4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V4z"/>
              </svg>
            = date.day
        - else
          = link_to date.day, path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>fiber note</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container-fluid p-0">
      <div class="row no-gutters">

        <nav class="col-md-2 nav flex-column bg-dark">
          <h5 class="nav-link pt-3 text-light">fiber note</h5 class="nav-link">

          <a class="nav-link text-light" href="<%= note_path %>">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-journals" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M3 2h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2h1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1H1a2 2 0 0 1 2-2z"/>
              <path d="M5 0h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2v-1a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1H3a2 2 0 0 1 2-2zM1 6v-.5a.5.5 0 0 1 1 0V6h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V9h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
            </svg>
            Notes & Tags
          </a>

          <a class="nav-link text-light" href="<%= calendar_path %>">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-calendar3" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
              <path fill-rule="evenodd" d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            </svg>
            Calendar
          </a>

          <a class="nav-link text-light" href="<%= network_path %>">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-bezier2" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M1 2.5A1.5 1.5 0 0 1 2.5 1h1A1.5 1.5 0 0 1 5 2.5v1A1.5 1.5 0 0 1 3.5 5h-1A1.5 1.5 0 0 1 1 3.5v-1zM2.5 2a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM11 12.5a1.5 1.5 0 0 1 1.5-1.5h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"/>
              <path fill-rule="evenodd" d="M6.767 4.645C6.303 3.923 5.592 3.5 4.5 3.5v-1H10v1H7.124c.18.18.34.381.484.605.638.992.892 2.354.892 3.895 0 1.993.257 3.092.713 3.7.418.559 1.089.8 2.287.8v1H6v-1h2.577a2.839 2.839 0 0 1-.165-.2C7.743 11.407 7.5 10.007 7.5 8c0-1.46-.246-2.597-.733-3.355z"/>
              <path d="M11 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM7 13a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
            </svg>
            Network graph
          </a>
        </nav>

        <%= yield %>

      </div>
    </div>

  </body>
</html>

app/views/network/show.haml
#network-show.col-md-10.bg-light{data: {controller: 'network', network_nodes: @nodes.to_json, network_edges: @edges.to_json}}
  = render partial: 'shared/github_corner'

  #graph{data: {target: 'network.graph'}}

app/views/notes/_nav.haml
%ul#notes-nav.col-md-2.list-group.list-group-flush.overflow-auto
  -# .list-group-item
  -#   .input-group.my-3
  -#     %input.form-control{type: 'text'}
  -#     .input-group-append
  -#       %span.input-group-text icon

  -# TODO icon
  - active = controller_name == 'notes' && action_name == 'new'
  %a.list-group-item.list-group-item-secondary{href: new_note_path, class: ( 'active' if active )}
    new

  - @notes.each do |note|
    - active = note == @note
    %a.list-group-item.list-group-item-secondary{href: edit_note_path(note), class: ( 'active' if active )}
      = note.title
  - @no_note_tags.each do |tag|
    %a.list-group-item.list-group-item-secondary{href: new_note_from_tag_path(tag)}
      = tag

app/views/notes/_note_editor.haml
-# locals: note
:ruby
  note_data = {
    controller: 'note',
    note: {
      id: note.id,
      title: note.title,
      content: note.to_note_doc.to_json,
      available_tags: available_tags
    }
  }

.note-editor.text-dark.p-3{data: note_data}
  .banner
    .loader.spinner-border.spinner-border-sm.text-secondary{data: {target: 'note.loader'}}
    .title-merger{data: {target: 'note.titleMerger'}} title merger

app/views/notes/edit.haml
= render Notes::NavComponent.new(notes: @notes, no_note_tags: @no_note_tags)

.col-md-8.bg-light
  = render Notes::EditorComponent.new(@note)
  -# #linked-blocks
  -#   = render partial: 'block_editor', collection: @linked_blocks, as: :block

app/views/notes/show.haml
= render Notes::NavComponent.new(@note)

.col-md-8.bg-light{data: {controller: 'notes--editor-wrapper', action: 'click->notes--editor-wrapper#click'}}
  = render partial: 'shared/github_corner'

  = render Notes::EditorComponent.new(@note)

  #linked-blocks
    - @linked_blocks.each do |block|
      .linked-block.border-top
        %p.text-muted.ml-3.mt-3
          :plain
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-link" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M6.354 5.5H4a3 3 0 0 0 0 6h3a3 3 0 0 0 2.83-4H9c-.086 0-.17.01-.25.031A2 2 0 0 1 7 10.5H4a2 2 0 1 1 0-4h1.535c.218-.376.495-.714.82-1z"/>
              <path d="M9 5.5a3 3 0 0 0-2.83 4h1.098A2 2 0 0 1 9 6.5h3a2 2 0 1 1 0 4h-1.535a4.02 4.02 0 0 1-.82 1H12a3 3 0 1 0 0-6H9z"/>
            </svg>

          linked block from
          = link_to block.root_note.title, note_path(title: block.root_note.title)

        = render Notes::EditorComponent.new(block)

app/views/session/new.haml
#session-new.col-md-10.d-flex.justify-content-center.align-items-center
  = form_with scope: :session, url: session_path do |f|
    - if flash[:error]
      .alert.alert-warning
        = flash[:error]
    = f.password_field :password, placeholder: 'password', class: 'form-control mb-3'
    = f.submit 'sign in', class: 'btn btn-block btn-primary'